### ISSUE TITLE
SCH-9 Добавить в pom.xml профиль для сонара

### ISSUE THREAD

**Issue by Werton25** [Werton25/schedule#14]

**Comment by AntonSidarau** [comment]
На будущее: прописывается в ~/.m2/settings.xml 

<settings>
	<pluginGroups>
			<pluginGroup>org.sonarsource.scanner.maven</pluginGroup>
	</pluginGroups>
	<profiles>
		<profile>
			<id>sonar</id>
			<activation>
				<activeByDefault>true</activeByDefault>
			</activation>
			<properties>
				<sonar.jdbc.url>
				  jdbc:mysql://localhost:3306/sonar?useUnicode=true&amp;characterEncoding=utf8
				</sonar.jdbc.url>
				<sonar.jdbc.username>root</sonar.jdbc.username>
				<sonar.jdbc.password>root</sonar.jdbc.password>
				<sonar.host.url>
				  http://localhost:9000/
				</sonar.host.url>
			</properties>
		</profile>
	 </profiles>
</settings>
